### ISSUE TITLE
Can `getindex(Atoms, i)` return a different type?

### ISSUE THREAD

**Issue by rkurchin** [SimonEnsemble/Xtals.jl#102]
👋 Hi there! Along with a few other people, I've been working on a Julia interface for atomic geometries (https://github.com/JuliaMolSim/AtomsBase.jl), which we think could really help unify the community of folks who work on representing and simulating these kinds of systems in Julia. As a test, I've been trying to implement the interface on this package, and one snag I've run into is that `getindex(Atoms,i)` where `i` is a single integer returns another `Atoms` object as opposed to some kind of `Atom` object. In the way we envision the interface, this is an issue because we expect a separate type to be returned (see `AbstractParticle` vs. `AbstractSystem`). In practice of course, many times this return will in effect just be a "view" of the larger collection (think of e.g. a `DataFrameRow`), especially if the system is represented in a SoA type fashion.

So anyway, all this is to ask, would you be open to defining something like an `Atom` type that would be a representation of a single atom in this way? I'm happy to draft a PR with this change if so.

FWIW, @mfherbst (lead developer of DFTK) and I hope to use this package as an initial demonstration of the power of the interface by using Xtals to read in a structure from a CIF file and pass it to DFTK for a simulation. Currently, DFTK relies on PyCall to ASE for this so having a "pure-Julia" solution will be very cool!

**Comment by eahenle** [comment]
Hi!

Yes, we can do that 👍  Agree, having a Julia pipeline for DFT will be very cool.  Definitely open to that PR.

**Comment by SimonEnsemble** [comment]
:wave: 
wow, that's awesome! we are happy to have `Xtals.jl` be used by others. :smile: 

so you're thinking to adopt the types/functions in `matter.jl` [here](https://github.com/SimonEnsemble/Xtals.jl/blob/master/src/matter.jl) for other packages?

actually our original implementation was
```julia
struct Atom
  species::Symbol
  coord::Coord
end
```
then we stored the atoms in the crystal as `Array{Atom}`. but this turned out to be too slow for looping over the coordinates. we are using these types for molecular simulations in `PorousMaterials.jl` so it's important that it is very fast to loop over the coords. e.g. [this optimized function](https://github.com/SimonEnsemble/PorousMaterials.jl/blob/master/src/vdw_energetics.jl#L25-L47) for vdw interactions.

but I think you are proposing to just create an extra type, `Atom`, to return when we call `get_index(atoms::Atoms, i)` and keep `Crystal` as is? but would this break any functions in `PorousMaterials.jl` @eahenle?

I think it would break our functions that take sliced `Crystal`s, at least when we only want a single atom from it.

**Comment by eahenle** [comment]
We would need to patch `get_index(xtal::Crystal, i)` for the new atom-slice behavior.  Functions that work on `xtal.atoms.coords` shouldn't be affected by this change, but functions that do anything like `xtal.atoms[i]` may be.  The syntax `xtal.atoms[i].coords` will still work, so not technically *broken*, but should be changed to `xtal.atoms.coords[i]` for speed.

**Comment by SimonEnsemble** [comment]
@eahenle good call.
seems like we just write a special constructor for when you try to construct a `Crystal` with an `Atom` instead of `Atoms` (and convert the `Atom` to `Atoms`) will do the trick.
